#**E-commerce Sales Analysis**

Using the **Ecommerce Sales** dataset

In [1]:
import pandas as pd

df = pd.read_csv(r"/content/drive/MyDrive/Colab Notebooks/IDRA/Day8_Ecommerce_Sales_Dataset.csv")
df = pd.DataFrame(df)
df

,Order_ID,Order_Date,Customer,City,Region,Category,Product,Quantity,Unit_Price,Discount_Percent,Total_Sales,Rating,Payment_Method
0,1001,2026-02-27,Kabir Ali,Hyderabad,South,Electronics,Wireless Headphones,3,1499,0,4497.00,3.8,Cash on Delivery
1,1002,2026-01-24,Aditya Verma,Jammu,North,Sports,Running Shoes,1,2799,0,2799.00,4.1,Cash on Delivery
2,1003,2026-04-18,Sara Ahmed,Chennai,South,Electronics,Power Bank,2,1199,15,2038.30,4.6,Cash on Delivery
3,1004,2026-03-13,Kabir Ali,Lucknow,North,Electronics,Mechanical Keyboard,4,2499,5,9496.20,4.1,Debit Card
4,1005,2026-03-30,Priya Menon,Jammu,North,Electronics,Smart Watch,1,3299,5,3134.05,4.2,UPI
...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,1096,2026-01-26,Aditya Verma,Kochi,South,Sports,Dumbbell Set,5,1999,5,9495.25,4.2,Credit Card
96,1097,2026-02-02,Arjun Nair,Mumbai,West,Clothing,T-Shirt,1,799,15,679.15,3.5,UPI
97,1098,2026-01-04,Yusuf Dar,Bengaluru,South,Home & Kitchen,Electric Kettle,4,1499,0,5996.00,4.2,Net Banking
98,1099,2026-03-06,Hiba Sheikh,Ahmedabad,West,Books,Machine Learning Basics,2,999,0,1998.00,3.8,UPI
99,1100,2026-02-08,Kabir Ali,Pune,West,Books,Data Science Handbook,5,899,0,4495.00,4.8,Debit Card

In [2]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 13 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Order_ID          100 non-null    int64
 1   Order_Date        100 non-null    object
 2   Customer          100 non-null    object
 3   City              100 non-null    object
 4   Region            100 non-null    object
 5   Category          100 non-null    object
 6   Product           100 non-null    object
 7   Quantity          100 non-null    int64
 8   Unit_Price        100 non-null    int64
 9   Discount_Percent  100 non-null    int64
 10  Total_Sales       100 non-null    float64
 11  Rating            100 non-null    float64
 12  Payment_Method    100 non-null    object
dtypes: float64(2), int64(4), object(7)
memory usage: 10.3+ KB

#Data selection

##Single column

In [3]:
df["Product"]

0         Wireless Headphones
1               Running Shoes
2                  Power Bank
3         Mechanical Keyboard
4                 Smart Watch
               ...
95               Dumbbell Set
96                    T-Shirt
97            Electric Kettle
98    Machine Learning Basics
99      Data Science Handbook
Name: Product, Length: 100, dtype: object

##Multiple columns

In [4]:
df[['Product', 'Quantity', 'Unit_Price']]

                    Product  Quantity  Unit_Price
0       Wireless Headphones         3        1499
1             Running Shoes         1        2799
2                Power Bank         2        1199
3       Mechanical Keyboard         4        2499
4               Smart Watch         1        3299
..                      ...       ...         ...
95             Dumbbell Set         5        1999
96                  T-Shirt         1         799
97          Electric Kettle         4        1499
98  Machine Learning Basics         2         999
99    Data Science Handbook         5         899

[100 rows x 3 columns]

##Specific rows

In [5]:
df.iloc[5:10]

,Order_ID,Order_Date,Customer,City,Region,Category,Product,Quantity,Unit_Price,Discount_Percent,Total_Sales,Rating,Payment_Method
5,1006,2026-01-21,Manya Rao,Kochi,South,Books,The Alchemist,1,499,10,449.1,4.2,Cash on Delivery
6,1007,2026-01-12,Alina Shah,Jaipur,North,Home & Kitchen,Water Bottle,2,699,0,1398.0,4.1,Debit Card
7,1008,2026-04-27,Aman Kumar,Jammu,North,Clothing,Hoodie,4,1599,5,6076.2,4.3,Credit Card
8,1009,2026-06-05,Aman Kumar,Mumbai,West,Home & Kitchen,Electric Kettle,3,1499,0,4497.0,4.0,Cash on Delivery
9,1010,2026-03-11,Aman Kumar,Kochi,South,Clothing,Jacket,4,2499,10,8996.4,4.7,Credit Card

In [6]:
df.iloc[[24,83,50]]

,Order_ID,Order_Date,Customer,City,Region,Category,Product,Quantity,Unit_Price,Discount_Percent,Total_Sales,Rating,Payment_Method
24,1025,2026-01-02,Rohan Mehta,Chennai,South,Sports,Football,5,799,0,3995.0,5.0,UPI
83,1084,2026-06-19,Aisha Mir,Kolkata,East,Electronics,Wireless Mouse,5,899,10,4045.5,3.8,Cash on Delivery
50,1051,2026-04-28,Aisha Mir,Bhubaneswar,East,Electronics,Smart Watch,2,3299,0,6598.0,4.2,Credit Card

##Combo of rows and columns

In [7]:
#customer details of order_no 1071
df.iloc[72, [2,3,4]]

Customer    Sara Ahmed
City           Kolkata
Region            East
Name: 72, dtype: object

In [8]:
df.loc[(df['Order_ID']==1026) | (df['Order_ID']==1027), ['Customer','City']]

      Customer        City
25  Sara Ahmed  Chandigarh
26  Sara Ahmed  Chandigarh

#Filtering

In [9]:
df[df['Total_Sales']>10000]

,Order_ID,Order_Date,Customer,City,Region,Category,Product,Quantity,Unit_Price,Discount_Percent,Total_Sales,Rating,Payment_Method
12,1013,2026-03-09,Maryam Khan,Lucknow,North,Clothing,Jacket,5,2499,15,10620.75,4.8,Net Banking
47,1048,2026-06-24,Sara Ahmed,Lucknow,North,Home & Kitchen,Coffee Maker,3,3499,0,10497.00,5.0,UPI
48,1049,2026-03-02,Ishita Gupta,Mumbai,West,Sports,Running Shoes,5,2799,0,13995.00,4.0,Net Banking
52,1053,2026-01-08,Ananya Singh,Hyderabad,South,Sports,Running Shoes,5,2799,5,13295.25,4.2,Credit Card
84,1085,2026-01-28,Sana Malik,Hyderabad,South,Home & Kitchen,Coffee Maker,4,3499,10,12596.40,4.3,Net Banking
89,1090,2026-05-13,Aditya Verma,Lucknow,North,Sports,Cricket Bat,5,2499,0,12495.00,3.8,Credit Card

In [10]:
df[df['City']=='Kochi']

,Order_ID,Order_Date,Customer,City,Region,Category,Product,Quantity,Unit_Price,Discount_Percent,Total_Sales,Rating,Payment_Method
5,1006,2026-01-21,Manya Rao,Kochi,South,Books,The Alchemist,1,499,10,449.10,4.2,Cash on Delivery
9,1010,2026-03-11,Aman Kumar,Kochi,South,Clothing,Jacket,4,2499,10,8996.40,4.7,Credit Card
34,1035,2026-05-03,Dev Patel,Kochi,South,Home & Kitchen,Coffee Maker,1,3499,15,2974.15,4.7,Credit Card
41,1042,2026-06-20,Manya Rao,Kochi,South,Home & Kitchen,Water Bottle,5,699,0,3495.00,4.2,UPI
63,1064,2026-02-07,Aman Kumar,Kochi,South,Books,Atomic Habits,4,599,0,2396.00,3.5,UPI
74,1075,2026-05-17,Aarav Sharma,Kochi,South,Clothing,Jeans,2,1899,15,3228.30,4.5,Cash on Delivery
85,1086,2026-06-16,Arjun Nair,Kochi,South,Clothing,Jeans,2,1899,15,3228.30,4.8,Cash on Delivery
90,1091,2026-06-26,Hiba Sheikh,Kochi,South,Books,Atomic Habits,5,599,0,2995.00,5.0,Net Banking
95,1096,2026-01-26,Aditya Verma,Kochi,South,Sports,Dumbbell Set,5,1999,5,9495.25,4.2,Credit Card

#Sorting

##In ascending order

In [11]:
df.sort_values(by='Total_Sales')

,Order_ID,Order_Date,Customer,City,Region,Category,Product,Quantity,Unit_Price,Discount_Percent,Total_Sales,Rating,Payment_Method
5,1006,2026-01-21,Manya Rao,Kochi,South,Books,The Alchemist,1,499,10,449.10,4.2,Cash on Delivery
62,1063,2026-04-17,Aman Kumar,Chandigarh,North,Books,The Alchemist,1,499,10,449.10,4.8,Credit Card
73,1074,2026-03-28,Alina Shah,Lucknow,North,Books,Atomic Habits,1,599,10,539.10,5.0,Net Banking
96,1097,2026-02-02,Arjun Nair,Mumbai,West,Clothing,T-Shirt,1,799,15,679.15,3.5,UPI
60,1061,2026-05-12,Alina Shah,Bengaluru,South,Books,Python Programming,1,749,5,711.55,5.0,Cash on Delivery
...,...,...,...,...,...,...,...,...,...,...,...,...,...
12,1013,2026-03-09,Maryam Khan,Lucknow,North,Clothing,Jacket,5,2499,15,10620.75,4.8,Net Banking
89,1090,2026-05-13,Aditya Verma,Lucknow,North,Sports,Cricket Bat,5,2499,0,12495.00,3.8,Credit Card
84,1085,2026-01-28,Sana Malik,Hyderabad,South,Home & Kitchen,Coffee Maker,4,3499,10,12596.40,4.3,Net Banking
52,1053,2026-01-08,Ananya Singh,Hyderabad,South,Sports,Running Shoes,5,2799,5,13295.25,4.2,Credit Card
48,1049,2026-03-02,Ishita Gupta,Mumbai,West,Sports,Running Shoes,5,2799,0,13995.00,4.0,Net Banking

##In descending order

In [12]:
df.sort_values(by='Total_Sales', ascending=False)

,Order_ID,Order_Date,Customer,City,Region,Category,Product,Quantity,Unit_Price,Discount_Percent,Total_Sales,Rating,Payment_Method
48,1049,2026-03-02,Ishita Gupta,Mumbai,West,Sports,Running Shoes,5,2799,0,13995.00,4.0,Net Banking
52,1053,2026-01-08,Ananya Singh,Hyderabad,South,Sports,Running Shoes,5,2799,5,13295.25,4.2,Credit Card
84,1085,2026-01-28,Sana Malik,Hyderabad,South,Home & Kitchen,Coffee Maker,4,3499,10,12596.40,4.3,Net Banking
89,1090,2026-05-13,Aditya Verma,Lucknow,North,Sports,Cricket Bat,5,2499,0,12495.00,3.8,Credit Card
12,1013,2026-03-09,Maryam Khan,Lucknow,North,Clothing,Jacket,5,2499,15,10620.75,4.8,Net Banking
...,...,...,...,...,...,...,...,...,...,...,...,...,...
60,1061,2026-05-12,Alina Shah,Bengaluru,South,Books,Python Programming,1,749,5,711.55,5.0,Cash on Delivery
96,1097,2026-02-02,Arjun Nair,Mumbai,West,Clothing,T-Shirt,1,799,15,679.15,3.5,UPI
73,1074,2026-03-28,Alina Shah,Lucknow,North,Books,Atomic Habits,1,599,10,539.10,5.0,Net Banking
5,1006,2026-01-21,Manya Rao,Kochi,South,Books,The Alchemist,1,499,10,449.10,4.2,Cash on Delivery
62,1063,2026-04-17,Aman Kumar,Chandigarh,North,Books,The Alchemist,1,499,10,449.10,4.8,Credit Card

##Using multiple columns

In [13]:
df.sort_values(by=['Category','Rating'])

,Order_ID,Order_Date,Customer,City,Region,Category,Product,Quantity,Unit_Price,Discount_Percent,Total_Sales,Rating,Payment_Method
15,1016,2026-03-06,Manya Rao,Pune,West,Books,The Alchemist,4,499,15,1696.60,3.5,UPI
63,1064,2026-02-07,Aman Kumar,Kochi,South,Books,Atomic Habits,4,599,0,2396.00,3.5,UPI
45,1046,2026-01-03,Ananya Singh,Delhi,North,Books,The Alchemist,4,499,15,1696.60,3.8,Credit Card
98,1099,2026-03-06,Hiba Sheikh,Ahmedabad,West,Books,Machine Learning Basics,2,999,0,1998.00,3.8,UPI
44,1045,2026-03-27,Reyansh Jain,Jammu,North,Books,Machine Learning Basics,1,999,0,999.00,4.0,Debit Card
...,...,...,...,...,...,...,...,...,...,...,...,...,...
24,1025,2026-01-02,Rohan Mehta,Chennai,South,Sports,Football,5,799,0,3995.00,5.0,UPI
35,1036,2026-06-02,Rohan Mehta,Srinagar,North,Sports,Yoga Mat,2,899,0,1798.00,5.0,Credit Card
37,1038,2026-03-08,Aditya Verma,Pune,West,Sports,Dumbbell Set,5,1999,5,9495.25,5.0,Debit Card
55,1056,2026-04-21,Rohan Mehta,Srinagar,North,Sports,Dumbbell Set,2,1999,5,3798.10,5.0,Debit Card
59,1060,2026-04-24,Karan Joshi,Pune,West,Sports,Dumbbell Set,3,1999,10,5397.30,5.0,Credit Card

#Overall Sales Statistics

In [14]:
print("Total sales: ", df['Total_Sales'].sum())
print("Average sales: ", df['Total_Sales'].mean())
print("Total no. of orders: ", df['Order_ID'].count())
print("Total no. of quantities sold: ", df['Quantity'].sum())

Total sales:  447262.95000000007
Average sales:  4472.629500000001
Total no. of orders:  100
Total no. of quantities sold:  294

In [15]:
max_sales = df['Total_Sales'].max()
print("\nHighest sales: ", max_sales, " by")
df[df['Total_Sales']==max_sales]

Highest sales:  13995.0  by

,Order_ID,Order_Date,Customer,City,Region,Category,Product,Quantity,Unit_Price,Discount_Percent,Total_Sales,Rating,Payment_Method
48,1049,2026-03-02,Ishita Gupta,Mumbai,West,Sports,Running Shoes,5,2799,0,13995.0,4.0,Net Banking

In [16]:
min_sales = df['Total_Sales'].min()
print("\nLowest sales: ", min_sales, " by")
df[df['Total_Sales']==min_sales]

Lowest sales:  449.1  by

,Order_ID,Order_Date,Customer,City,Region,Category,Product,Quantity,Unit_Price,Discount_Percent,Total_Sales,Rating,Payment_Method
5,1006,2026-01-21,Manya Rao,Kochi,South,Books,The Alchemist,1,499,10,449.1,4.2,Cash on Delivery
62,1063,2026-04-17,Aman Kumar,Chandigarh,North,Books,The Alchemist,1,499,10,449.1,4.8,Credit Card

After analysing, we can see that
- running sports (5) bought by Ishita Gupta is the highest individual sales in this dataset
- book The Alchemist bought by 2 customers Manya Rao and Aman Kumar are the smallest individual sales

#Groupby

##Category wise Analysis

In [17]:
cat_total_sales = df.groupby('Category')['Total_Sales']
print("Total sales:\n", cat_total_sales.sum())
print("\nAverage sales:\n", cat_total_sales.mean())
print("\nBest performing catgory: ", cat_total_sales.sum().idxmax())
print("Worst performing catgory: ", cat_total_sales.sum().idxmin())

Total sales:
 Category
Books              36792.40
Clothing           69028.20
Electronics        92086.00
Home & Kitchen    113329.90
Sports            136026.45
Name: Total_Sales, dtype: float64

Average sales:
 Category
Books             1752.019048
Clothing          4930.585714
Electronics       4846.631579
Home & Kitchen    5396.661905
Sports            5441.058000
Name: Total_Sales, dtype: float64

Best performing catgory:  Sports
Worst performing catgory:  Books

In [18]:
cat_quan = df.groupby('Category')['Quantity']
print("Total quantities: \n", cat_quan.sum())

cat_ord = df.groupby('Category')['Order_ID'].count()
print("\n\nNo. of orders per category:\n", cat_ord)
print("\nCategory with highest no. of orders:\n", cat_ord[cat_ord==cat_ord.max()])

Total quantities:
 Category
Books             60
Clothing          39
Electronics       57
Home & Kitchen    59
Sports            79
Name: Quantity, dtype: int64


No. of orders per category:
 Category
Books             21
Clothing          14
Electronics       19
Home & Kitchen    21
Sports            25
Name: Order_ID, dtype: int64

Category with highest no. of orders:
 Category
Sports    25
Name: Order_ID, dtype: int64

According to categories, we can see that
- Sports is the best performing category
- also Sports is the category with highest quantity sold

##City wise analysis

In [19]:
city_total_sales = df.groupby('City')['Total_Sales'].sum()
print("Total sales per city:\n", city_total_sales)
print("\nCity with highest total sales: ", city_total_sales.idxmax())
print("City with lowest total sales: ", city_total_sales.idxmin())

Total sales per city:
 City
Ahmedabad      14788.70
Bengaluru      13524.30
Bhubaneswar     6598.00
Chandigarh     34539.65
Chennai        47493.20
Delhi          30882.80
Hyderabad      59076.45
Jaipur         25534.00
Jammu          16059.75
Kochi          37257.50
Kolkata        20169.00
Lucknow        46194.65
Mumbai         41457.80
Pune           41908.55
Srinagar       11778.60
Name: Total_Sales, dtype: float64

City with highest total sales:  Hyderabad
City with lowest total sales:  Bhubaneswar

In [20]:
city_quan = df.groupby('City')['Quantity'].sum()
print("Total quantities per city: ", city_quan)
print("\nCity with highest quantity sold: ", city_quan.idxmax())

city_ord = df.groupby('City')['Order_ID'].count()
print("\n\nNo. of orders per city: ", city_ord)
print("\nCity with highest no. of orders:\n", city_ord[city_ord==city_ord.max()])

Total quantities per city:  City
Ahmedabad      12
Bengaluru      14
Bhubaneswar     2
Chandigarh     22
Chennai        29
Delhi          18
Hyderabad      25
Jaipur         17
Jammu          11
Kochi          29
Kolkata        24
Lucknow        22
Mumbai         23
Pune           34
Srinagar       12
Name: Quantity, dtype: int64

City with highest quantity sold:  Pune


No. of orders per city:  City
Ahmedabad       6
Bengaluru       4
Bhubaneswar     1
Chandigarh      8
Chennai        10
Delhi           6
Hyderabad       7
Jaipur          7
Jammu           6
Kochi           9
Kolkata         7
Lucknow         6
Mumbai          8
Pune           10
Srinagar        5
Name: Order_ID, dtype: int64

City with highest no. of orders:
 City
Chennai    10
Pune       10
Name: Order_ID, dtype: int64

Grouping by city,
- Hyderabad has the highest total sales
- Pune has most no. of quantities sold
- the highest no. of orders come from Chennai and Pune

##Product wise analysis

In [21]:
prod_total_sales = df.groupby('Product')['Total_Sales'].sum()
print("Total sales per product:\n", prod_total_sales)
print("\nTop-selling product: ", prod_total_sales.idxmax())
print("Least-selling product: ", prod_total_sales.idxmin())

Total sales per product:
 Product
Atomic Habits              11590.65
Coffee Maker               51610.25
Cricket Bat                41483.40
Data Science Handbook       4495.00
Dumbbell Set               30184.90
Electric Kettle            26382.40
Football                   10307.10
Hoodie                      7675.20
Jacket                     47106.15
Jeans                       6456.60
Machine Learning Basics     5694.30
Mechanical Keyboard        26489.40
Mixer Grinder              25341.55
Power Bank                  6474.60
Python Programming          7527.45
Running Shoes              41285.25
Smart Watch                15670.25
T-Shirt                     7790.25
The Alchemist               7485.00
Water Bottle                9995.70
Wireless Headphones        33877.40
Wireless Mouse              9574.35
Yoga Mat                   12765.80
Name: Total_Sales, dtype: float64

Top-selling product:  Coffee Maker
Least-selling product:  Data Science Handbook

In [22]:
prod_no = df.groupby('Product')['Quantity'].sum()
print("Total quantities per product:\n", prod_no)
print("\nProduct with highest quantity sold: ", prod_no.idxmax(), "(", prod_no.max(), ")")
print("Product with lowest quantity sold: ", prod_no.idxmin(), "(", prod_no.min(), ")")

Total quantities per product:
 Product
Atomic Habits              21
Coffee Maker               16
Cricket Bat                18
Data Science Handbook       5
Dumbbell Set               16
Electric Kettle            19
Football                   14
Hoodie                      5
Jacket                     20
Jeans                       4
Machine Learning Basics     6
Mechanical Keyboard        11
Mixer Grinder               9
Power Bank                  6
Python Programming         11
Running Shoes              15
Smart Watch                 5
T-Shirt                    10
The Alchemist              17
Water Bottle               15
Wireless Headphones        23
Wireless Mouse             12
Yoga Mat                   16
Name: Quantity, dtype: int64

Product with highest quantity sold:  Wireless Headphones ( 23 )
Product with lowest quantity sold:  Jeans ( 4 )

In [23]:
prod_ord = df.groupby('Product')['Order_ID'].count()
print("Total orders per product:\n", prod_ord)
print("\nProduct with highest no. of orders: ", prod_ord.idxmax(), "(", prod_ord.max(), ")")
print("Product with lowest no. of orders: ", prod_ord.idxmin(), "(", prod_ord.min(), ")")

Total orders per product:
 Product
Atomic Habits              6
Coffee Maker               7
Cricket Bat                5
Data Science Handbook      1
Dumbbell Set               5
Electric Kettle            5
Football                   4
Hoodie                     2
Jacket                     5
Jeans                      2
Machine Learning Basics    4
Mechanical Keyboard        3
Mixer Grinder              4
Power Bank                 3
Python Programming         4
Running Shoes              5
Smart Watch                3
T-Shirt                    5
The Alchemist              6
Water Bottle               5
Wireless Headphones        7
Wireless Mouse             3
Yoga Mat                   6
Name: Order_ID, dtype: int64

Product with highest no. of orders:  Coffee Maker ( 7 )
Product with lowest no. of orders:  Data Science Handbook ( 1 )

We can see that
- Coffee Maker is the top selling product
- Wireless headHeadphones had the most no. of quantities sold
- Largest no. of orders come in for Coffee Maker

##Payment Method

In [24]:
pay = df.groupby('Payment_Method')['Total_Sales'].sum()
print("Total sales per payment method:\n", pay)
print("\nPayment method with highest sales: ", pay.idxmax())
print("Payment method with lowest sales: ", pay.idxmin())

Total sales per payment method:
 Payment_Method
Cash on Delivery     50123.30
Credit Card         106540.25
Debit Card           98064.90
Net Banking          96371.25
UPI                  96163.25
Name: Total_Sales, dtype: float64

Payment method with highest sales:  Credit Card
Payment method with lowest sales:  Cash on Delivery

In [25]:
pay_ord = df.groupby('Payment_Method')['Order_ID'].count()
print("Total orders per payment method:\n", pay_ord)
print("\nPayment method with highest no. of orders: ", pay_ord.idxmax())
print("Payment method with lowest no. of orders: ", pay_ord.idxmin())

Total orders per payment method:
 Payment_Method
Cash on Delivery    15
Credit Card         22
Debit Card          20
Net Banking         17
UPI                 26
Name: Order_ID, dtype: int64

Payment method with highest no. of orders:  UPI
Payment method with lowest no. of orders:  Cash on Delivery

We can see that
- Most sales are paid using credit card

##Filtering

In [26]:
print("Sales more than 10000:")
df[df['Total_Sales'] > 10000]

Sales more than 10000:

,Order_ID,Order_Date,Customer,City,Region,Category,Product,Quantity,Unit_Price,Discount_Percent,Total_Sales,Rating,Payment_Method
12,1013,2026-03-09,Maryam Khan,Lucknow,North,Clothing,Jacket,5,2499,15,10620.75,4.8,Net Banking
47,1048,2026-06-24,Sara Ahmed,Lucknow,North,Home & Kitchen,Coffee Maker,3,3499,0,10497.00,5.0,UPI
48,1049,2026-03-02,Ishita Gupta,Mumbai,West,Sports,Running Shoes,5,2799,0,13995.00,4.0,Net Banking
52,1053,2026-01-08,Ananya Singh,Hyderabad,South,Sports,Running Shoes,5,2799,5,13295.25,4.2,Credit Card
84,1085,2026-01-28,Sana Malik,Hyderabad,South,Home & Kitchen,Coffee Maker,4,3499,10,12596.40,4.3,Net Banking
89,1090,2026-05-13,Aditya Verma,Lucknow,North,Sports,Cricket Bat,5,2499,0,12495.00,3.8,Credit Card

In [27]:
print("Purchases made in the Sports category")
df[df['Category']=='Sports']

Purchases made in the Sports category

,Order_ID,Order_Date,Customer,City,Region,Category,Product,Quantity,Unit_Price,Discount_Percent,Total_Sales,Rating,Payment_Method
1,1002,2026-01-24,Aditya Verma,Jammu,North,Sports,Running Shoes,1,2799,0,2799.00,4.1,Cash on Delivery
11,1012,2026-04-12,Aman Kumar,Chandigarh,North,Sports,Cricket Bat,2,2499,10,4498.20,4.6,Credit Card
13,1014,2026-02-05,Dev Patel,Jaipur,North,Sports,Running Shoes,3,2799,0,8397.00,4.6,UPI
16,1017,2026-03-17,Sana Malik,Hyderabad,South,Sports,Cricket Bat,3,2499,0,7497.00,4.0,Net Banking
20,1021,2026-01-18,Reyansh Jain,Chandigarh,North,Sports,Yoga Mat,1,899,10,809.10,4.7,Credit Card
22,1023,2026-06-21,Aman Kumar,Jaipur,North,Sports,Football,3,799,10,2157.30,4.3,Net Banking
23,1024,2026-02-27,Rohan Mehta,Jaipur,North,Sports,Running Shoes,1,2799,0,2799.00,4.3,UPI
24,1025,2026-01-02,Rohan Mehta,Chennai,South,Sports,Football,5,799,0,3995.00,5.0,UPI
26,1027,2026-05-02,Sara Ahmed,Chandigarh,North,Sports,Football,5,799,15,3395.75,4.6,Net Banking
30,1031,2026-01-04,Rohan Mehta,Ahmedabad,West,Sports,Yoga Mat,1,899,15,764.15,4.1,Credit Card
35,1036,2026-06-02,Rohan Mehta,Srinagar,North,Sports,Yoga Mat,2,899,0,1798.00,5.0,Credit Card
37,1038,2026-03-08,Aditya Verma,Pune,West,Sports,Dumbbell Set,5,1999,5,9495.25,5.0,Debit Card
39,1040,2026-05-18,Aditya Verma,Ahmedabad,West,Sports,Dumbbell Set,1,1999,0,1999.00,4.7,Debit Card
48,1049,2026-03-02,Ishita Gupta,Mumbai,West,Sports,Running Shoes,5,2799,0,13995.00,4.0,Net Banking
52,1053,2026-01-08,Ananya Singh,Hyderabad,South,Sports,Running Shoes,5,2799,5,13295.25,4.2,Credit Card
54,1055,2026-02-18,Arjun Nair,Chennai,South,Sports,Yoga Mat,4,899,15,3056.60,3.5,Net Banking
55,1056,2026-04-21,Rohan Mehta,Srinagar,North,Sports,Dumbbell Set,2,1999,5,3798.10,5.0,Debit Card
58,1059,2026-01-01,Mehak Bhat,Chennai,South,Sports,Cricket Bat,4,2499,15,8496.60,4.2,Credit Card
59,1060,2026-04-24,Karan Joshi,Pune,West,Sports,Dumbbell Set,3,1999,10,5397.30,5.0,Credit Card
71,1072,2026-05-03,Aarav Sharma,Jaipur,North,Sports,Yoga Mat,5,899,10,4045.50,4.3,Debit Card
81,1082,2026-06-23,Rahul Das,Jammu,North,Sports,Yoga Mat,3,899,15,2292.45,4.5,Credit Card
82,1083,2026-06-25,Priya Menon,Jammu,North,Sports,Football,1,799,5,759.05,3.8,Cash on Delivery
89,1090,2026-05-13,Aditya Verma,Lucknow,North,Sports,Cricket Bat,5,2499,0,12495.00,3.8,Credit Card
92,1093,2026-05-16,Aisha Mir,Hyderabad,South,Sports,Cricket Bat,4,2499,15,8496.60,4.5,Cash on Delivery
95,1096,2026-01-26,Aditya Verma,Kochi,South,Sports,Dumbbell Set,5,1999,5,9495.25,4.2,Credit Card

In [28]:
print("Top 10 highest individual sales")
df.sort_values('Total_Sales', ascending=False).head(10)

Top 10 highest individual sales

,Order_ID,Order_Date,Customer,City,Region,Category,Product,Quantity,Unit_Price,Discount_Percent,Total_Sales,Rating,Payment_Method
48,1049,2026-03-02,Ishita Gupta,Mumbai,West,Sports,Running Shoes,5,2799,0,13995.00,4.0,Net Banking
52,1053,2026-01-08,Ananya Singh,Hyderabad,South,Sports,Running Shoes,5,2799,5,13295.25,4.2,Credit Card
84,1085,2026-01-28,Sana Malik,Hyderabad,South,Home & Kitchen,Coffee Maker,4,3499,10,12596.40,4.3,Net Banking
89,1090,2026-05-13,Aditya Verma,Lucknow,North,Sports,Cricket Bat,5,2499,0,12495.00,3.8,Credit Card
12,1013,2026-03-09,Maryam Khan,Lucknow,North,Clothing,Jacket,5,2499,15,10620.75,4.8,Net Banking
47,1048,2026-06-24,Sara Ahmed,Lucknow,North,Home & Kitchen,Coffee Maker,3,3499,0,10497.00,5.0,UPI
69,1070,2026-06-30,Aditya Verma,Delhi,North,Clothing,Jacket,4,2499,0,9996.00,3.8,Net Banking
79,1080,2026-05-25,Aditya Verma,Delhi,North,Clothing,Jacket,4,2499,0,9996.00,4.6,Debit Card
51,1052,2026-03-13,Rohan Mehta,Chandigarh,North,Electronics,Mechanical Keyboard,4,2499,5,9496.20,4.2,Debit Card
3,1004,2026-03-13,Kabir Ali,Lucknow,North,Electronics,Mechanical Keyboard,4,2499,5,9496.20,4.1,Debit Card