Using three datasets:
- Orders.csv
- Customers.csv
- Products.csv

In [1]:
import pandas as pd
import numpy as np
import datetime as dt

In [2]:
ord_df = pd.read_csv(r'/content/drive/MyDrive/Colab Notebooks/IDRA/Day9_Orders.csv')
cust_df = pd.read_csv(r'/content/drive/MyDrive/Colab Notebooks/IDRA/Day9_Customers.csv')
prod_df = pd.read_csv(r'/content/drive/MyDrive/Colab Notebooks/IDRA/Day9_Products.csv')

In [3]:
ord_df = pd.DataFrame(ord_df)
cust_df = pd.DataFrame(cust_df)
prod_df = pd.DataFrame(prod_df)

#Order dataset

In [4]:
ord_df.head()

,Order_ID,Order_Date,Customer_ID,Product_ID,Quantity,Payment_Method,Order_Status
0,O0001,2026-02-19,C027,P019,2,Credit Card,Delivered
1,O0002,2026-01-25,C006,P003,2,Debit Card,Delivered
2,O0003,2026-02-26,C015,P004,1,Cash on Delivery,Delivered
3,O0004,2026-03-04,C024,P015,3,Net Banking,Delivered
4,O0005,2026-03-29,C025,P009,5,Credit Card,Delivered

In [5]:
ord_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 120 entries, 0 to 119
Data columns (total 7 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Order_ID        120 non-null    object
 1   Order_Date      120 non-null    object
 2   Customer_ID     120 non-null    object
 3   Product_ID      120 non-null    object
 4   Quantity        120 non-null    int64
 5   Payment_Method  120 non-null    object
 6   Order_Status    120 non-null    object
dtypes: int64(1), object(6)
memory usage: 6.7+ KB

#Customer dataset

In [6]:
cust_df.head()

  Customer_ID Customer_Name      City Region Membership_Type
0        C001  Aarav Sharma  Srinagar  North         Premium
1        C002     Zoya Khan     Delhi  North         Regular
2        C003   Rohan Mehta    Mumbai   West         Premium
3        C004  Ananya Singh     Jammu  North         Regular
4        C005     Kabir Ali   Lucknow  North             New

In [7]:
cust_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 5 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Customer_ID      30 non-null     object
 1   Customer_Name    30 non-null     object
 2   City             30 non-null     object
 3   Region           30 non-null     object
 4   Membership_Type  30 non-null     object
dtypes: object(5)
memory usage: 1.3+ KB

#Product dataset

In [8]:
prod_df.head()

  Product_ID         Product_Name     Category  Unit_Price     Brand
0       P001  Wireless Headphones  Electronics        1499  SoundMax
1       P002  Mechanical Keyboard  Electronics        2499    KeyPro
2       P003       Wireless Mouse  Electronics         899  TechGear
3       P004          Smart Watch  Electronics        3299   FitTech
4       P005           Power Bank  Electronics        1199  VoltPlus

In [9]:
prod_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Product_ID    20 non-null     object
 1   Product_Name  20 non-null     object
 2   Category      20 non-null     object
 3   Unit_Price    20 non-null     int64
 4   Brand         20 non-null     object
dtypes: int64(1), object(4)
memory usage: 932.0+ bytes

#Merging datasets

In [10]:
ord_cust = pd.merge(ord_df, cust_df, on='Customer_ID')
ord_cust.head()

,Order_ID,Order_Date,Customer_ID,Product_ID,Quantity,Payment_Method,Order_Status,Customer_Name,City,Region,Membership_Type
0,O0001,2026-02-19,C027,P019,2,Credit Card,Delivered,Harsh Vardhan,Noida,North,Premium
1,O0002,2026-01-25,C006,P003,2,Debit Card,Delivered,Ishita Gupta,Bengaluru,South,Premium
2,O0003,2026-02-26,C015,P004,1,Cash on Delivery,Delivered,Karan Joshi,Chandigarh,North,Regular
3,O0004,2026-03-04,C024,P015,3,Net Banking,Delivered,Maryam Khan,Hyderabad,South,Regular
4,O0005,2026-03-29,C025,P009,5,Credit Card,Delivered,Reyansh Jain,Kolkata,East,New

In [11]:
ord_cust_prod = pd.merge(ord_cust, prod_df, on='Product_ID')
ord_cust_prod.head()

,Order_ID,Order_Date,Customer_ID,Product_ID,Quantity,Payment_Method,Order_Status,Customer_Name,City,Region,Membership_Type,Product_Name,Category,Unit_Price,Brand
0,O0001,2026-02-19,C027,P019,2,Credit Card,Delivered,Harsh Vardhan,Noida,North,Premium,Cricket Bat,Sports,2499,BatPro
1,O0002,2026-01-25,C006,P003,2,Debit Card,Delivered,Ishita Gupta,Bengaluru,South,Premium,Wireless Mouse,Electronics,899,TechGear
2,O0003,2026-02-26,C015,P004,1,Cash on Delivery,Delivered,Karan Joshi,Chandigarh,North,Regular,Smart Watch,Electronics,3299,FitTech
3,O0004,2026-03-04,C024,P015,3,Net Banking,Delivered,Maryam Khan,Hyderabad,South,Regular,Machine Learning Basics,Books,999,AIPress
4,O0005,2026-03-29,C025,P009,5,Credit Card,Delivered,Reyansh Jain,Kolkata,East,New,Coffee Maker,Home & Kitchen,3499,HomeBrew

###Removing unnecessary columns

In [12]:
ord_cust_prod.drop(['Customer_ID', 'Product_ID'], axis=1, inplace=True)
ord_cust_prod

,Order_ID,Order_Date,Quantity,Payment_Method,Order_Status,Customer_Name,City,Region,Membership_Type,Product_Name,Category,Unit_Price,Brand
0,O0001,2026-02-19,2,Credit Card,Delivered,Harsh Vardhan,Noida,North,Premium,Cricket Bat,Sports,2499,BatPro
1,O0002,2026-01-25,2,Debit Card,Delivered,Ishita Gupta,Bengaluru,South,Premium,Wireless Mouse,Electronics,899,TechGear
2,O0003,2026-02-26,1,Cash on Delivery,Delivered,Karan Joshi,Chandigarh,North,Regular,Smart Watch,Electronics,3299,FitTech
3,O0004,2026-03-04,3,Net Banking,Delivered,Maryam Khan,Hyderabad,South,Regular,Machine Learning Basics,Books,999,AIPress
4,O0005,2026-03-29,5,Credit Card,Delivered,Reyansh Jain,Kolkata,East,New,Coffee Maker,Home & Kitchen,3499,HomeBrew
...,...,...,...,...,...,...,...,...,...,...,...,...,...
115,O0116,2026-02-19,1,Net Banking,Delivered,Reyansh Jain,Kolkata,East,New,Electric Kettle,Home & Kitchen,1499,KitchenPro
116,O0117,2026-02-21,3,Cash on Delivery,Shipped,Yusuf Dar,Srinagar,North,New,Machine Learning Basics,Books,999,AIPress
117,O0118,2026-03-09,4,Credit Card,Delivered,Reyansh Jain,Kolkata,East,New,Atomic Habits,Books,599,MindReads
118,O0119,2026-02-03,2,Debit Card,Delivered,Karan Joshi,Chandigarh,North,Regular,Cricket Bat,Sports,2499,BatPro
119,O0120,2026-01-21,1,Cash on Delivery,Cancelled,Rahul Das,Kolkata,East,Regular,Dumbbell Set,Sports,1999,StrongFit

In [13]:
df = ord_cust_prod[['Order_ID', 'Order_Date', 'Customer_Name', 'City', 'Region', 'Category', 'Product_Name', 'Quantity', 'Unit_Price', 'Brand', 'Payment_Method', 'Order_Status', 'Membership_Type']]
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 120 entries, 0 to 119
Data columns (total 13 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Order_ID         120 non-null    object
 1   Order_Date       120 non-null    object
 2   Customer_Name    120 non-null    object
 3   City             120 non-null    object
 4   Region           120 non-null    object
 5   Category         120 non-null    object
 6   Product_Name     120 non-null    object
 7   Quantity         120 non-null    int64
 8   Unit_Price       120 non-null    int64
 9   Brand            120 non-null    object
 10  Payment_Method   120 non-null    object
 11  Order_Status     120 non-null    object
 12  Membership_Type  120 non-null    object
dtypes: int64(2), object(11)
memory usage: 12.3+ KB

#DateTime processing

In [14]:
df['Order_Date'] = pd.to_datetime(df['Order_Date'])
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 120 entries, 0 to 119
Data columns (total 13 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Order_ID         120 non-null    object
 1   Order_Date       120 non-null    datetime64[ns]
 2   Customer_Name    120 non-null    object
 3   City             120 non-null    object
 4   Region           120 non-null    object
 5   Category         120 non-null    object
 6   Product_Name     120 non-null    object
 7   Quantity         120 non-null    int64
 8   Unit_Price       120 non-null    int64
 9   Brand            120 non-null    object
 10  Payment_Method   120 non-null    object
 11  Order_Status     120 non-null    object
 12  Membership_Type  120 non-null    object
dtypes: datetime64[ns](1), int64(2), object(10)
memory usage: 12.3+ KB

In [15]:
df['Order_Date'] = df['Order_Date'].dt.strftime('%d-%m-%Y')
df.head(3)

,Order_ID,Order_Date,Customer_Name,City,Region,Category,Product_Name,Quantity,Unit_Price,Brand,Payment_Method,Order_Status,Membership_Type
0,O0001,19-02-2026,Harsh Vardhan,Noida,North,Sports,Cricket Bat,2,2499,BatPro,Credit Card,Delivered,Premium
1,O0002,25-01-2026,Ishita Gupta,Bengaluru,South,Electronics,Wireless Mouse,2,899,TechGear,Debit Card,Delivered,Premium
2,O0003,26-02-2026,Karan Joshi,Chandigarh,North,Electronics,Smart Watch,1,3299,FitTech,Cash on Delivery,Delivered,Regular

In [16]:
x = df[df['Order_ID']=='O0001']['Order_Date']
x = pd.to_datetime(x, format='%d-%m-%Y')
print(x)

print('\nDateTime Info of the Order_ID O0001:')
print("Date = ", x.dt.day.values[0])
print("Month = ", x.dt.month.values[0])
print("Year = ", x.dt.year.values[0])

print("\nDerived Info:")
print("Day = ", x.dt.day_name().values[0])
print("Day of the week = ", x.dt.day_of_week.values[0])
print("Month name = ", x.dt.month_name().values[0])
print("Quarter = ", x.dt.quarter.values[0])
print("Day of the year = ", x.dt.dayofyear.values[0])
print("Week of the year = ", x.dt.isocalendar().week.values[0])

0   2026-02-19
Name: Order_Date, dtype: datetime64[ns]

DateTime Info of the Order_ID O0001:
Date =  19
Month =  2
Year =  2026

Derived Info:
Day =  Thursday
Day of the week =  3
Month name =  February
Quarter =  1
Day of the year =  50
Week of the year =  8

In [17]:
df['Order_Date'] = pd.to_datetime(df['Order_Date'])

/tmp/ipykernel_55627/2524311366.py:1: UserWarning: Parsing dates in %d-%m-%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df['Order_Date'] = pd.to_datetime(df['Order_Date'])

#Adding new column, Total_Amount

In [18]:
def tot_amt(row):
  return row['Quantity'] * row['Unit_Price']

df['Total_Amount'] = df.apply(tot_amt, axis=1)
df = df[['Order_ID', 'Order_Date', 'Customer_Name', 'City', 'Region', 'Category', 'Product_Name', 'Quantity', 'Unit_Price', 'Total_Amount', 'Brand', 'Payment_Method', 'Order_Status', 'Membership_Type']]
df

,Order_ID,Order_Date,Customer_Name,City,Region,Category,Product_Name,Quantity,Unit_Price,Total_Amount,Brand,Payment_Method,Order_Status,Membership_Type
0,O0001,2026-02-19,Harsh Vardhan,Noida,North,Sports,Cricket Bat,2,2499,4998,BatPro,Credit Card,Delivered,Premium
1,O0002,2026-01-25,Ishita Gupta,Bengaluru,South,Electronics,Wireless Mouse,2,899,1798,TechGear,Debit Card,Delivered,Premium
2,O0003,2026-02-26,Karan Joshi,Chandigarh,North,Electronics,Smart Watch,1,3299,3299,FitTech,Cash on Delivery,Delivered,Regular
3,O0004,2026-03-04,Maryam Khan,Hyderabad,South,Books,Machine Learning Basics,3,999,2997,AIPress,Net Banking,Delivered,Regular
4,O0005,2026-03-29,Reyansh Jain,Kolkata,East,Home & Kitchen,Coffee Maker,5,3499,17495,HomeBrew,Credit Card,Delivered,New
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
115,O0116,2026-02-19,Reyansh Jain,Kolkata,East,Home & Kitchen,Electric Kettle,1,1499,1499,KitchenPro,Net Banking,Delivered,New
116,O0117,2026-02-21,Yusuf Dar,Srinagar,North,Books,Machine Learning Basics,3,999,2997,AIPress,Cash on Delivery,Shipped,New
117,O0118,2026-03-09,Reyansh Jain,Kolkata,East,Books,Atomic Habits,4,599,2396,MindReads,Credit Card,Delivered,New
118,O0119,2026-02-03,Karan Joshi,Chandigarh,North,Sports,Cricket Bat,2,2499,4998,BatPro,Debit Card,Delivered,Regular
119,O0120,2026-01-21,Rahul Das,Kolkata,East,Sports,Dumbbell Set,1,1999,1999,StrongFit,Cash on Delivery,Cancelled,Regular

#Processing new dataframe

In [19]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 120 entries, 0 to 119
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Order_ID         120 non-null    object
 1   Order_Date       120 non-null    datetime64[ns]
 2   Customer_Name    120 non-null    object
 3   City             120 non-null    object
 4   Region           120 non-null    object
 5   Category         120 non-null    object
 6   Product_Name     120 non-null    object
 7   Quantity         120 non-null    int64
 8   Unit_Price       120 non-null    int64
 9   Total_Amount     120 non-null    int64
 10  Brand            120 non-null    object
 11  Payment_Method   120 non-null    object
 12  Order_Status     120 non-null    object
 13  Membership_Type  120 non-null    object
dtypes: datetime64[ns](1), int64(3), object(10)
memory usage: 13.3+ KB

In [20]:
df.isnull().sum() # no null values

Order_ID           0
Order_Date         0
Customer_Name      0
City               0
Region             0
Category           0
Product_Name       0
Quantity           0
Unit_Price         0
Total_Amount       0
Brand              0
Payment_Method     0
Order_Status       0
Membership_Type    0
dtype: int64

In [21]:
df.drop_duplicates() # no duplicates

,Order_ID,Order_Date,Customer_Name,City,Region,Category,Product_Name,Quantity,Unit_Price,Total_Amount,Brand,Payment_Method,Order_Status,Membership_Type
0,O0001,2026-02-19,Harsh Vardhan,Noida,North,Sports,Cricket Bat,2,2499,4998,BatPro,Credit Card,Delivered,Premium
1,O0002,2026-01-25,Ishita Gupta,Bengaluru,South,Electronics,Wireless Mouse,2,899,1798,TechGear,Debit Card,Delivered,Premium
2,O0003,2026-02-26,Karan Joshi,Chandigarh,North,Electronics,Smart Watch,1,3299,3299,FitTech,Cash on Delivery,Delivered,Regular
3,O0004,2026-03-04,Maryam Khan,Hyderabad,South,Books,Machine Learning Basics,3,999,2997,AIPress,Net Banking,Delivered,Regular
4,O0005,2026-03-29,Reyansh Jain,Kolkata,East,Home & Kitchen,Coffee Maker,5,3499,17495,HomeBrew,Credit Card,Delivered,New
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
115,O0116,2026-02-19,Reyansh Jain,Kolkata,East,Home & Kitchen,Electric Kettle,1,1499,1499,KitchenPro,Net Banking,Delivered,New
116,O0117,2026-02-21,Yusuf Dar,Srinagar,North,Books,Machine Learning Basics,3,999,2997,AIPress,Cash on Delivery,Shipped,New
117,O0118,2026-03-09,Reyansh Jain,Kolkata,East,Books,Atomic Habits,4,599,2396,MindReads,Credit Card,Delivered,New
118,O0119,2026-02-03,Karan Joshi,Chandigarh,North,Sports,Cricket Bat,2,2499,4998,BatPro,Debit Card,Delivered,Regular
119,O0120,2026-01-21,Rahul Das,Kolkata,East,Sports,Dumbbell Set,1,1999,1999,StrongFit,Cash on Delivery,Cancelled,Regular

#To csv file

In [22]:
df.to_csv(r'/content/drive/MyDrive/Colab Notebooks/IDRA/Day9_processed_ecommerce.csv')